// Map information
export const GET_PLACE_BY_LOCATION = 'GET_PLACE_BY_LOCATION';
export const GET_PLACE_BY_LOCATION_SUCCESS = 'GET_PLACE_BY_LOCATION_SUCCESS';
export const GET_PLACE_BY_LOCATION_FAILED = 'GET_PLACE_BY_LOCATION_FAILED';