export const REGISTER_TOKEN = 'REGISTER_TOKEN';
export const REGISTER_TOKEN_SUCCESS = 'REGISTER_TOKEN_SUCCESS';
export const REGISTER_TOKEN_FAILED = 'REGISTER_TOKEN_FAILED';

export const GET_LIST_NOTI = 'GET_LIST_NOTI';
export const GET_LIST_NOTI_SUCCESS = 'GET_LIST_NOTI_SUCCESS';
export const GET_LIST_NOTI_FAILED = 'GET_LIST_NOTI_FAILED';
