const APP_NAME = {
  SPLASH: 'Splash',
  ONBOARDING: 'Onboarding',
  AUTH: 'Auth',
  DASHBOARD: 'Dashboard',
  LOGIN: 'Login',
  REGISTER: 'Register',
  FORGOT: 'Forgot',
  DASHBOARD_TAB: 'DashboardTabNavigator',
  HOME: 'Home',
  LIST_MY_RESERVATION: 'ListMyReservation',
  POST: 'Post',
  NOTIFICATION: 'Notification',
  PROFILE: 'Profile',
  MAP_VIEW: 'MapViewScreen',
  TRIP_DETAIL: 'TripDetail',
  NOTIFICATION_DETAIL: 'NotificationDetailScreen',
  CAR_MANAGEMENT: 'CarManagement',
  REGISTER_CAR: 'RegisterCar',
  TRIP_USER_DETAIL: 'TripUserDetail',
};
module.exports = APP_NAME;
