// Car information
export const REGISTER_CAR = 'REGISTER_CAR';
export const REGISTER_CAR_SUCCESS = 'REGISTER_CAR_SUCCESS';
export const REGISTER_CAR_FAILED = 'REGISTER_CAR_FAILED';

export const GET_LIST_MY_CAR = 'GET_LIST_MY_CARS';
export const GET_LIST_MY_CARS_SUCCESS = 'GET_LIST_MY_CARS_SUCCESS';
export const GET_LIST_MY_CARS_FAILED = 'GET_LIST_MY_CARS_FAILED';

export const DELETE_LIST_MY_CAR = 'DELETE_LIST_MY_CAR';
export const DELETE_LIST_MY_CAR_SUCCESS = 'DELETE_LIST_MY_CAR_SUCCESS';
export const DELETE_LIST_MY_CAR_FAILED = 'DELETE_LIST_MY_CAR_FAILED';
