// Find trip information
export const FIND_TRIP = 'FIND_TRIP';
export const FIND_TRIP_SUCCESS = 'FIND_TRIP_SUCCESS';
export const FIND_TRIP_FAILED = 'FIND_TRIP_FAILED';

export const TAKE_TRIP = 'TAKE_TRIP';
export const TAKE_TRIP_SUCCESS = 'TAKE_TRIP_SUCCESS';
export const TAKE_TRIP_FAILED = 'TAKE_TRIP_FAILED';

export const GET_LIST_TRIP_USER = 'GET_LIST_TRIP_USER';
export const GET_LIST_TRIP_USER_SUCCESS = 'GET_LIST_TRIP_USER_SUCCESS';
export const GET_LIST_TRIP_USER_FAILED = 'GET_LIST_TRIP_USER_FAILED';

export const CANCEL_TRIP = 'CANCEL_TRIP';
export const CANCEL_TRIP_SUCCESS = 'CANCEL_TRIP_SUCCESS';
export const CANCEL_TRIP_FAILED = 'CANCEL_TRIP_FAILED';
