// Map information
export const GET_PLACE_BY_LOCATION = 'GET_PLACE_BY_LOCATION';
export const GET_PLACE_BY_LOCATION_SUCCESS = 'GET_PLACE_BY_LOCATION_SUCCESS';
export const GET_PLACE_BY_LOCATION_FAILED = 'GET_PLACE_BY_LOCATION_FAILED';

export const SEARCH_ADDRESS = 'SEARCH_ADDRESS';
export const SEARCH_ADDRESS_SUCCESS = 'SEARCH_ADDRESS_SUCCESS';
export const SEARCH_ADDRESS_FAILED = 'SEARCH_ADDRESS_FAILED';

export const GET_ROUTING = 'GET_ROUTING';
export const GET_ROUTING_SUCCESS = 'GET_ROUTING_SUCCESS';
export const GET_ROUTING_FAILED = 'GET_ROUTING_FAILED';
