// Find trip information
export const FIND_TRIP = 'FIND_TRIP';
export const FIND_TRIP_SUCCESS = 'FIND_TRIP_SUCCESS';
export const FIND_TRIP_FAILED = 'FIND_TRIP_FAILED';

export const GET_LIST_TRIP_DRIVER = 'GET_LIST_TRIP_DRIVER';
export const GET_LIST_TRIP_DRIVER_SUCCESS = 'GET_LIST_TRIP_DRIVER_SUCCESS';
export const GET_LIST_TRIP_DRIVER_FAILED = 'GET_LIST_TRIP_USER_FAILED';

export const MARK_DONE_TRIP = 'MARK_DONE_TRIP';
export const MARK_DONE_TRIP_SUCCESS = 'MARK_DONE_TRIP_SUCCESS';
export const MARK_DONE_TRIP_FAILED = 'MARK_DONE_TRIP_FAILED';
